#!/bin/bash
if [ $# -eq 0 ]
  then
    echo "Provide day as argument"
    exit
fi
token=$( cat aocsession.user )
curl --cookie "session=$token" https://adventofcode.com/2019/day/$1/input -o day$1.txt
echo 
cat day$1.txt
